### ISSUE TITLE
Click to install page not found

### ISSUE THREAD

**Issue by KevinParnell** [Chiiruno/OneeChan#2]
When I go to install this extension to Tampermonkey, I get a 404 GitHub page not found, same with the link to Stylechan.

**Comment by Choephel** [comment]
Use https://github.com/Chiiruno/OneeChan/raw/master/builds/OneeChan.user.js and it should prompt an install with Tampermonkey.

I can confirm it at least works on the latest Waterfox with Violentmonkey

**Comment by KevinParnell** [comment]
Thanks! I'll test it with the latest Tampermonkey on Safari 12.
